# Generated by Django 4.2.17 on 2024-12-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelovehiculo',
            name='categoria',
            field=models.CharField(choices=[('PARTICULAR', 'PARTICULAR'), ('TRANSPORTE', 'TRANSPORTE'), ('DE CARGA', 'DE CARGA')], default='PARTICULAR', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='modelovehiculo',
            name='marca',
            field=models.CharField(choices=[('FIAT', 'FIAT'), ('CHEVROLET', 'CHEVROLET'), ('FORD', 'FORD'), ('TOYOTA', 'TOYOTA')], default='FORD', max_length=20, verbose_name='Marca'),
        ),
    ]
